feat: add mermaid projeto arquitetural #19
tallysdev/eventSync pull request #29
Opened 2024-04-16 14:08 UTC by italo-mauricio

Mermaid adicionado para melhor visualização do projeto arquitetural

Closes #19

2024-04-19 20:25 UTC, tallysdev approved these changes

2024-04-19 20:33 UTC, tallysdev approved these changes
Ficou muito top!!

2024-04-21 15:07 UTC, mts-lucas requested changes
A conexão do backend com o front está incorreta, na arquitetura rest o front end (no caso o vue) não interage de forma alguma com o model, o vue so interage com o as rotas que por sua vez interagem com o serializer, esse sim interage com os models, e tem o fator que comentei anteriormente que as views podem interagir diretamento com os models tambem, nao pelo serializer. Aqui esta um exemplo de como dever ser no back.

![image](https://github.com/tallysdev/eventSync/assets/100450081/fbdaa0e4-f345-4219-a407-93b87f5ee6b9)

esse é um exemplo basico da conexão do vue com o back 

![image](https://github.com/tallysdev/eventSync/assets/100450081/f3345ce9-ec46-4e21-87cc-cfa052673005)

LEMBRE DE ADICIONAR NO HISTORICO DE REVISÕES

2024-04-22 15:55 UTC, tallysdev commented
[updating mental map](https://github.com/tallysdev/eventSync/pull/29/commits/42967d710b6d0a118b128a536923dd53b04ecbc6) https://github.com/tallysdev/eventSync/issues/19

O texto do commit deve representar oq foi feito na ação. Atualizou oq? Quem? Onde? Como? O que comem? Onde habitam, hoje no globo repórter.

https://github.com/iuricode/padroes-de-commits?tab=readme-ov-file 
https://www.conventionalcommits.org/pt-br/v1.0.0/
https://semver.org/lang/pt-BR/

2024-04-22 23:00 UTC, mts-lucas submitted a review, later dismissed

2024-04-23 11:34 UTC, DayXL submitted a review, later dismissed
Ótimo trabalho, aprovado.

2024-04-23 13:02 UTC, ViniciusMaiaM submitted a review, later dismissed

2024-04-24 18:50 UTC, DayXL approved these changes

2024-04-24 18:51 UTC, merged