Doc/issue18 att userstories
tallysdev/eventSync pull request #30
Opened 2024-04-19 00:20 UTC by tallysdev

2024-04-19 13:04 UTC, DayXL commented
1. Na tabela Histórico de revisões ajeitar a última linha, tem ortografia duas vezes.
2. O US02 tem cara de "manter avaliação", mudar o nome e melhorar detalhamento.
3. No US03 o que seria o "sistema de reservas"? Não foi citado na descrição do US03.
4. O US04 seria uma "manter patrocinador"? Caso não, o que seria? Não devia existir um US para isso?
5. O US05 não é um "manter participante"? Não está bem descrito e detalhado, falta atualizar e consultar. Na descrição fala sobre autorizar participante, mas não tem nada sobre isso nos requisitos que serão usados.
6.  No US08 existe um requisito "cadastrar mensagem", acho que ele deveria virar um "manter mensagem".

2024-04-19 20:36 UTC, italo-mauricio submitted a review, later dismissed

2024-04-20 13:28 UTC, DayXL approved these changes
Ok, já podemos passar para a atualização de requisitos.

2024-04-21 21:24 UTC, tallysdev commented
> Ok, já podemos passar para a atualização de requisitos.

Falta @mts-lucas e @ViniciusMaiaM  verem, mas já estou fazendo os requisitos, mesmo sabendo que vou ter que refazer kk

2024-04-22 12:23 UTC, ViniciusMaiaM requested changes

2024-04-22 12:23 UTC, ViniciusMaiaM commented on docs/doc-userStories.md
> +| US06 | Calendário de eventos
Os Users Stories 6 e 11 estão com o mesmo nome, mas com descrições diferentes. Eles deveriam compor o mesmo user storie ou realmente são separados?

2024-04-22 12:23 UTC, ViniciusMaiaM commented on docs/doc-userStories.md
> +### User Story US012 - Eventos Relacionados
User Story nomeada como "US012", corrigir para "US12" para assim ficar no padrão das outras

2024-04-22 12:23 UTC, ViniciusMaiaM commented on docs/doc-userStories.md
>  | ------------- | :------------------------------------------------------------- |
Os US5, 10, 11 e 12 apresentam essas linhas a mais, o que acaba modificando a formatação padrão que está sendo seguida nos outros US. Por favor modifique.

2024-04-22 12:23 UTC, ViniciusMaiaM commented on docs/doc-userStories.md
> +|---|---
A partir deste ponto há uma mudança na formatação da descrição do US, onde o cabeçalho de "Descrição" deixa de ficar em negrito e o conteúdo do US13 está todo em negrito. Por favor corrigir para seguir o padrão anteriormente definido.

2024-04-22 14:55 UTC, mts-lucas reviewed
No US08 falava sobre eventos favoritos, mas não vi nenhum outro lugar citando essa opção.

No US10 - Acho interessante mostrar a Taciano já que da ultima vez ficou diferente oque estavamos pensando pro sistema e o que ele realmente queria, não sei se na visão dele isso de reserva se encaixa.

No US16 - Acho valido dar uma detalhada melhor no objetivo desse US, se esse cracha é so informativo, ou se ele vai ter um QRcode ou algo do genero pra marcar presença.

Aproveitando o embalo acho que deveriamos ter algo associado a esse registro de presença nao??? Temos o gerador de certificado, mas acho que tem que ter uma forma do gerente do evento conseguir inserir presença, ou isso ja ficou em outro US q nao percebi?

2024-04-22 15:50 UTC, tallysdev commented on docs/doc-userStories.md
> +|---|---
Quando existe apenas uma linha na tabela o markdown coloca como negrito automaticamente, mas vou modificar para deixar todos no padrão.

2024-04-22 17:36 UTC, tallysdev commented
> No US08 falava sobre eventos favoritos, mas não vi nenhum outro lugar citando essa opção.
> 
> No US10 - Acho interessante mostrar a Taciano já que da ultima vez ficou diferente oque estavamos pensando pro sistema e o que ele realmente queria, não sei se na visão dele isso de reserva se encaixa.
> 
> No US16 - Acho valido dar uma detalhada melhor no objetivo desse US, se esse cracha é so informativo, ou se ele vai ter um QRcode ou algo do genero pra marcar presença.
> 
> Aproveitando o embalo acho que deveriamos ter algo associado a esse registro de presença nao??? Temos o gerador de certificado, mas acho que tem que ter uma forma do gerente do evento conseguir inserir presença, ou isso ja ficou em outro US q nao percebi?

Posso colocar no de manter eventos, oq acha?

2024-04-23 11:12 UTC, DayXL submitted a review, later dismissed
Ele mudou o que foi pedido, está ok.

2024-04-23 12:56 UTC, ViniciusMaiaM approved these changes
Tá show!

2024-04-23 12:59 UTC, DayXL approved these changes
Aprovado.

2024-04-23 12:59 UTC, merged