Modelo ER atualizado
tallysdev/eventSync pull request #37
Opened 2024-06-13 13:33 UTC by DayXL

O modelo antigo do ER foi refeito, agora ele se encontra mais atualizado e mais completo, foi adicionado mais entidades e suas respectivas relações.

2024-06-18 21:07 UTC, tallysdev requested changes
Achei vago a tabela de 'formulario' e 'comentario', achei essas tabelas soltas no diagrama. O  usuário faz um formulário de que? Para onde? E comenta em no que?

2024-06-19 00:09 UTC, ViniciusMaiaM requested changes
Concordo com o que foi falado por @tallysdev, acredito que as únicas mudanças necessárias sejam nas tabelas de formulário e comentário. Por que e para que elas existem, talvez revisar suas relações e o que elas devem fazer no sistema. Também acho necessário rever o que foi leventado no docs para discussão sobre as entidades, como, tipo de usuário e dados na tabela de presença.

2024-06-27 12:24 UTC, ViniciusMaiaM approved these changes
Acho que está ótimo

2024-06-29 21:03 UTC, tallysdev approved these changes

2024-06-29 21:03 UTC, merged