Feat: Sistema de Manter usuario, cadastro e login criados
tallysdev/eventSync pull request #44
Opened 2024-07-05 18:52 UTC by mts-lucas

O que foi feito:

- Endpoints de Login e registro de Usuario criado
- Sistema JWT criado
- Endpoints de listagem e edição de usuario criados

PS: Quando testarem/subirem as mudanças, apaguem o banco de dados atual antes

2024-07-06 14:47 UTC, italo-mauricio submitted a review, later dismissed

2024-07-06 17:07 UTC, DayXL requested changes
Ao iniciar o servidor de desenvolvimento e tentar acessar o endereço da aplicação, o seguinte erro foi achado:

"NoReverseMatch at /eventsync/api/v1/
Reverse for 'user_detail' with no arguments not found. 1 pattern(s) tried: ['eventsync/api/v1/users/(?P<pk>[0-9]+)/\\Z']"

Isso precisa ser revisto.

2024-07-06 20:41 UTC, mts-lucas commented
Avaliem com bastante calma o que foi feito, corrigi o erro que ocorreu e ja fiz novas modicicações

- Adicionado comando (precisa do csv que sera adicionado futuramente) para povoar o banco com usuarios
- Adicionado comando para criar superusuario, com ele sera possivel testar o funcionamento do endupoint users/pk ( no caso users/1)

Para usar o comando basta digitar no terminal

`python manage.py initadmin --help`

ele lhe mostrara os argumentos que precisa passar para usar o comando, depois disso basta usar o comando novamente 

`python manage.py initadmin <sequencia de argumentos>`

2024-07-07 15:13 UTC, DayXL approved these changes
- O manter usuário foi criado
- O cadastro foi criado, possui as seguintes validações de dados:

1.  Verifica tamanho do cpf, do telefone.
2.  Verifica se o email e o cpf já estão cadastrados.
3. Avisa sobre senhas fracas.
4. Você só se cadastra se respeitar o que foi dito anteriormente.

- Login criado, para logar gera token de acesso.
- Mostra detalhes de usuário.
- Registra super usuário. 

Aprovado.

2024-07-08 15:19 UTC, italo-mauricio approved these changes

2024-07-08 15:59 UTC, merged