Issue/manter evento
tallysdev/eventSync pull request #58
Opened 2024-07-24 19:41 UTC by italo-mauricio

2024-07-28 19:25 UTC, DayXL reviewed
- A tela está nos padrões das telas iniciais.
- Falta informações como: 
1. Data de 
início e fim, só tem um campo data de evento, trocar pelos dois falados. 
2. Quantidade máxima e mínima do evento.
3. Quantidade de horas
4 . Tipo do evento.

2024-08-09 22:22 UTC, ViniciusMaiaM requested changes
Remova os arquivos de dependências, package, das pastas de fora do frontend

2024-08-10 19:26 UTC, ViniciusMaiaM requested changes
Ótimo trabalho, só vou querer as seguintes mudanças antes de subir:
- Faça com que o botão de criar evento só seja clicavel quando todo o formulario estiver validado, já existe algo similar no arquivo SponsorForm
- Quando não existirem dados de locations exiba uma mensagem indicando isso no campo do forms
- Na função fetchLocations faça o mesmo que foi feito com a de event, crie um service e o chame no teu componente
- Passe o componente CreateEventPage para uma pasta, similar ao que foi feito em sponsors e home

2024-08-12 12:40 UTC, ViniciusMaiaM approved these changes
Ótimo trabalho

2024-08-12 18:00 UTC, DayXL approved these changes
Aprovado.

2024-08-12 18:56 UTC, ViniciusMaiaM approved these changes
Tudo certo!

2024-08-12 18:57 UTC, merged