Feat/issue57 - Endpoints de Eventos e locais criados
tallysdev/eventSync pull request #61
Opened 2024-07-26 19:05 UTC by mts-lucas

O que foi feito:
- Endpoints de locais criados
- Endpoints de eventos criados
- Comando para povoar o banco com eventos e locais criado

Antes de testar os endpoints rode logo o comando
`
python manage.py initevents`

2024-07-28 19:18 UTC, DayXL submitted a review, later dismissed
- Tem o crud completo do local, e todos os atributos que foram pensados até o momento.
- Tem o crud completo do evento, e todos os atributos que foram pensados até o momento.
- O comando povoa o banco e você consegue listar os eventos criados, para ver os locais você precisa de autorização.
- Sendo assim, aprovado.

2024-07-29 11:00 UTC, ViniciusMaiaM requested changes
Tudo show, só tá faltando os testes

2024-07-30 12:39 UTC, ViniciusMaiaM approved these changes
Tudo show

2024-07-30 14:48 UTC, DayXL approved these changes
Ok.

2024-07-30 16:15 UTC, merged